/* eslint-disable @next/next/no-img-element -- private R2 assets require the authenticated browser request */
"use client";
import { Check,CloudUpload,FileCode2,ImagePlus,LoaderCircle,Trash2,X } from "lucide-react";
import { useState } from "react";
import type { Brand,CharacterProfile,Skill } from "@/lib/types";
import { jsonRequest } from "./studio-app";

const defaultBrand:Brand={id:"",name:"",type:"تطبيق",category:"",description:"",website:"",audience:"",market:"اليمن",language:"العربية — لهجة يمنية",tone:"حديثة، واضحة، موثوقة",colors:["#6256E8","#F0EDFF","#17152A"],fonts:["Tajawal"],logoUrl:"",sourceText:"",sourceUrls:[],preferredCtas:"تواصل معنا لمعرفة التفاصيل",forbiddenPhrases:"",status:"ready"};
const defaultCharacter:CharacterProfile={id:"",name:"",role:"شخصية إعلانية",persona:"",appearance:"",wardrobe:"",voice:"",restrictions:"",brandIds:[],imageUrls:[],active:true};
const defaultSkill:Skill={id:"",name:"",description:"",category:"كتابة وتسويق",markdown:"",platforms:["instagram","facebook"],outputTypes:["image","text"],version:"1.0.0",active:true};
async function upload(file:File,purpose:string){const data=new FormData();data.set("file",file);data.set("purpose",purpose);const response=await fetch("/api/upload",{method:"POST",body:data});const body=await response.json() as {asset?:{url:string};error?:string};if(!response.ok||!body.asset)throw new Error(body.error||"تعذر رفع الملف");return body.asset.url}
function Modal({eyebrow,title,onClose,children,footer}:{eyebrow:string;title:string;onClose:()=>void;children:React.ReactNode;footer:React.ReactNode}){return <div className="modal-backdrop"><div className="editor-modal" role="dialog" aria-modal="true"><header><div><span>{eyebrow}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={20}/></button></header><div className="modal-body">{children}</div><footer>{footer}</footer></div></div>}
function Field({label,value,onChange,placeholder="",area=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;area?:boolean}){return <label className="field"><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
function StepTitle({n,title,text}:{n:string;title:string;text:string}){return <div className="step-title"><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></div>}

export function BrandModal({initial,onClose,onSaved}:{initial?:Brand;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [item,setItem]=useState<Brand>(initial||defaultBrand),[busy,setBusy]=useState(false),[error,setError]=useState("");const update=<K extends keyof Brand>(key:K,value:Brand[K])=>setItem(v=>({...v,[key]:value}));
  async function save(){setBusy(true);setError("");try{await jsonRequest("/api/brands",{method:"POST",body:JSON.stringify(item)});await onSaved()}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");setBusy(false)}}
  async function logo(file?:File){if(!file)return;setBusy(true);try{update("logoUrl",await upload(file,"brand-logo"))}catch(e){setError(e instanceof Error?e.message:"تعذر الرفع")}finally{setBusy(false)}}
  return <Modal eyebrow="ذاكرة البراند" title={initial?"تعديل البراند":"إضافة براند جديد"} onClose={onClose} footer={<><button className="ghost-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}حفظ البراند</button></>}>
    <section><StepTitle n="01" title="المعلومات الأساسية" text="عرّف النشاط والسوق والجمهور."/><div className="form-grid two"><Field label="اسم البراند *" value={item.name} onChange={v=>update("name",v)}/><label className="field"><span>نوع البراند</span><select value={item.type} onChange={e=>update("type",e.target.value)}>{["تطبيق","موقع","متجر","شركة","خدمة","منتج"].map(v=><option key={v}>{v}</option>)}</select></label><Field label="المجال" value={item.category} onChange={v=>update("category",v)} placeholder="تقنية، تجزئة، خدمات…"/><Field label="رابط الموقع" value={item.website} onChange={v=>update("website",v)} placeholder="https://"/><Field label="وصف البراند والمنتجات" value={item.description} onChange={v=>update("description",v)} area/><Field label="الجمهور المستهدف" value={item.audience} onChange={v=>update("audience",v)} area/><Field label="السوق والمناطق" value={item.market} onChange={v=>update("market",v)}/></div></section>
    <section><StepTitle n="02" title="الهوية البصرية والصوت" text="الشعار والألوان والخطوط والنبرة."/><div className="upload-identity"><div className="logo-preview">{item.logoUrl?<img src={item.logoUrl} alt="شعار البراند"/>:<b>{item.name?.[0]||"B"}</b>}</div><label className="upload-button"><ImagePlus size={18}/>رفع الشعار<input type="file" accept="image/*,.svg" onChange={e=>void logo(e.target.files?.[0])}/></label></div><div className="form-grid two"><Field label="الألوان — افصل بفاصلة" value={item.colors.join(", ")} onChange={v=>update("colors",v.split(",").map(x=>x.trim()).filter(Boolean))}/><Field label="الخطوط — افصل بفاصلة" value={item.fonts.join(", ")} onChange={v=>update("fonts",v.split(",").map(x=>x.trim()).filter(Boolean))}/><Field label="نبرة البراند" value={item.tone} onChange={v=>update("tone",v)}/><Field label="اللغة واللهجة" value={item.language} onChange={v=>update("language",v)}/><Field label="CTA المفضّل" value={item.preferredCtas} onChange={v=>update("preferredCtas",v)}/><Field label="عبارات ممنوعة" value={item.forbiddenPhrases} onChange={v=>update("forbiddenPhrases",v)}/></div></section>
    <section><StepTitle n="03" title="مصادر المعرفة" text="ألصق المحتوى أو أضف روابط Drive والموقع."/><Field label="محتوى ومعرفة البراند" value={item.sourceText} onChange={v=>update("sourceText",v)} placeholder="دليل الهوية، الخدمات، منشورات سابقة…" area/><Field label="روابط Google Drive أو صفحات الموقع — رابط في كل سطر" value={item.sourceUrls.join("\n")} onChange={v=>update("sourceUrls",v.split("\n").map(x=>x.trim()).filter(Boolean))} area/></section>{error&&<p className="form-error">{error}</p>}
  </Modal>
}

export function CharacterModal({initial,brands,onClose,onSaved}:{initial?:CharacterProfile;brands:Brand[];onClose:()=>void;onSaved:()=>Promise<void>}){
  const [item,setItem]=useState<CharacterProfile>(initial||defaultCharacter),[busy,setBusy]=useState(false),[error,setError]=useState("");const update=<K extends keyof CharacterProfile>(k:K,v:CharacterProfile[K])=>setItem(x=>({...x,[k]:v}));
  async function addImages(files:FileList|null){if(!files)return;setBusy(true);try{const urls=[...item.imageUrls];for(const file of Array.from(files).slice(0,5-urls.length))urls.push(await upload(file,"character-reference"));update("imageUrls",urls)}catch(e){setError(e instanceof Error?e.message:"تعذر الرفع")}finally{setBusy(false)}}
  async function save(){setBusy(true);setError("");try{await jsonRequest("/api/characters",{method:"POST",body:JSON.stringify(item)});await onSaved()}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");setBusy(false)}}
  return <Modal eyebrow="الشخصيات الإعلانية" title={initial?"تعديل الشخصية":"إضافة شخصية"} onClose={onClose} footer={<><button className="ghost-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}حفظ الشخصية</button></>}>
    <section><StepTitle n="01" title="الهوية والدور" text="من هي الشخصية وكيف تمثل البراند؟"/><div className="form-grid two"><Field label="اسم الشخصية *" value={item.name} onChange={v=>update("name",v)}/><Field label="الدور" value={item.role} onChange={v=>update("role",v)}/><Field label="البرسونا" value={item.persona} onChange={v=>update("persona",v)} area/><Field label="المظهر" value={item.appearance} onChange={v=>update("appearance",v)} area/><Field label="الملابس والأسلوب" value={item.wardrobe} onChange={v=>update("wardrobe",v)} area/><Field label="طريقة الكلام" value={item.voice} onChange={v=>update("voice",v)} area/><Field label="القيود" value={item.restrictions} onChange={v=>update("restrictions",v)} area/></div></section>
    <section><StepTitle n="02" title="الصور المرجعية" text="حتى 5 صور واضحة بزوايا مختلفة."/><label className="drop-zone"><CloudUpload size={27}/><strong>رفع صور الشخصية</strong><span>أمامية، جانبية، كاملة</span><input type="file" multiple accept="image/*" onChange={e=>void addImages(e.target.files)}/></label><div className="image-chip-row">{item.imageUrls.map((url,i)=><div key={url}><img src={url} alt={`مرجع ${i+1}`}/><button onClick={()=>update("imageUrls",item.imageUrls.filter(x=>x!==url))}><Trash2 size={13}/></button></div>)}</div></section>
    <section><StepTitle n="03" title="نطاق الاستخدام" text="حدد البراندات التي تستطيع استخدام الشخصية."/><div className="choice-chips"><button className={!item.brandIds.length?"selected":""} onClick={()=>update("brandIds",[])}>كل البراندات</button>{brands.map(b=><button key={b.id} className={item.brandIds.includes(b.id)?"selected":""} onClick={()=>update("brandIds",item.brandIds.includes(b.id)?item.brandIds.filter(x=>x!==b.id):[...item.brandIds,b.id])}>{b.name}</button>)}</div></section>{error&&<p className="form-error">{error}</p>}
  </Modal>
}

export function SkillModal({initial,onClose,onSaved}:{initial?:Skill;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [item,setItem]=useState<Skill>(initial||defaultSkill),[busy,setBusy]=useState(false),[error,setError]=useState("");const update=<K extends keyof Skill>(k:K,v:Skill[K])=>setItem(x=>({...x,[k]:v}));
  async function readFile(file?:File){if(!file)return;try{const text=await file.text();update("markdown",text);if(!item.name)update("name",file.name.replace(/\.md$/i,"").replaceAll("-"," "))}catch{setError("تعذر قراءة الملف")}}
  async function save(){setBusy(true);setError("");try{await jsonRequest("/api/skills",{method:"POST",body:JSON.stringify(item)});await onSaved()}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");setBusy(false)}}
  return <Modal eyebrow="مكتبة المهارات" title={initial?"تعديل المهارة":"رفع مهارة جديدة"} onClose={onClose} footer={<><button className="ghost-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}حفظ المهارة</button></>}>
    <label className="skill-drop"><FileCode2 size={28}/><strong>ارفع ملف SKILL.md</strong><span>أو اكتب التعليمات مباشرة في المحرر</span><b>اختيار ملف</b><input type="file" accept=".md,text/markdown,text/plain" onChange={e=>void readFile(e.target.files?.[0])}/></label>
    <div className="form-grid two"><Field label="اسم المهارة *" value={item.name} onChange={v=>update("name",v)}/><Field label="رقم الإصدار" value={item.version} onChange={v=>update("version",v)}/><Field label="التصنيف" value={item.category} onChange={v=>update("category",v)}/><Field label="وصف مختصر" value={item.description} onChange={v=>update("description",v)}/></div><label className="field code-field"><span>محتوى SKILL.md <small>{item.markdown.length} حرف</small></span><textarea value={item.markdown} onChange={e=>update("markdown",e.target.value)} placeholder="# Skill name\n\n## Purpose\n…"/></label>{error&&<p className="form-error">{error}</p>}
  </Modal>
}
